import Head from 'next/head';
import { Inter } from '@next/font/google';

const inter = Inter({ subsets: ['latin'] });

const Form = () => {
  return (
    <>
      <Head>
        <title>Panel Details | Open Climate Fix</title>
        <meta name="description" content="Generated by Neha and Ashay" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col items-center justify-start px-10 min-h-screen">
        <form
          onSubmit={async (e) => {
            e.preventDefault();
            try {
              const data = new FormData(e.currentTarget);
              console.log(data);
            } catch (e) {
              console.log(e);
            }
          }}
        >
          <div>
            <h1 className="font-bold text-4xl mt-20">Panel Details</h1>
          </div>
          <div className="my-8">
            <h2 className="font-medium text-lg">Solar panel direction</h2>
            <p className="text-ocf-gray-900 text-xs mt-1">
              (0º = North, 90º = East, 180º = South, 270º = West)
            </p>
            <input
              name="solarPanelDirection"
              type="number"
              placeholder="170º"
              className="mt-3 text-lg text-center bg-gray-50 border border-gray-300 text-gray-900 rounded-lg  block w-20 h-14 p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white"
            />
            <p className="text-ocf-gray-900 text-xs mt-1 underline">
              I don&apos;t know
            </p>
          </div>

          <div className="my-8">
            <h2 className="font-medium text-lg">Solar panel angle tilt</h2>
            <p className="text-ocf-gray-900 text-xs mt-1">
              (Degrees above the horizontal)
            </p>
            <input
              name="solarPanelAngelTilt"
              type="number"
              placeholder="30º"
              className="mt-3 text-lg text-center bg-gray-50 border border-gray-300 text-gray-900 rounded-lg block w-20 h-14 p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white "
            />
          </div>

          <div className="my-8">
            <div className="flex flex-row justify-start items-center w-full">
              <h2 className="font-medium text-lg">Solar panel capacity</h2>
              <p className="text-ocf-gray-900 text-xs mx-1">(optional)</p>
            </div>
            <input
              name="solarPanelCapacity"
              type="number"
              placeholder="3000 W"
              className="mt-3 text-lg text-center bg-gray-50 border border-gray-300 text-gray-900 rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-24 h-14 p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
            />
          </div>

          <div className="flex justify-center items-center w-full mt-24">
            <button className="bg-ocf-yellow shadow h-14 w-40 text-center rounded-md font-bold text-xl">
              NEXT
            </button>
          </div>
        </form>
      </main>
    </>
  );
};

export default Form;
